# Generated by Django 4.0 on 2021-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profilePicture',
            field=models.ImageField(upload_to='ProfilePictures/'),
        ),
    ]
