# Generated by Django 4.0 on 2021-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_people_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='ProfilePictures/'),
        ),
    ]
