# Generated by Django 4.0 on 2021-12-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_people_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profilePicture',
            field=models.ImageField(default='ProfilePictures/default.jpg', upload_to='ProfilePictures/'),
        ),
    ]
