# Generated by Django 4.0 on 2021-12-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_people_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=256),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=256),
        ),
    ]
