# Generated by Django 4.0 on 2021-12-28 18:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_people_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=256)),
                ('EventDescription', models.CharField(max_length=256)),
                ('EventLocation', models.CharField(max_length=256)),
                ('EventCategory', multiselectfield.db.fields.MultiSelectField(choices=[('Reading', 'Reading'), ('Cycling', 'Cycling'), ('Hiking', 'Hiking'), ('Drawing', 'Drawing'), ('Photography', 'Photography'), ('Swimming', 'Swimming'), ('Sleeping', 'Sleeping'), ('Sports', 'Sports'), ('Gaming', 'Gaming')], max_length=26)),
                ('EventStartTime', models.DateTimeField()),
            ],
        ),
    ]
