# Generated by Django 4.0 on 2021-12-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.people'),
        ),
    ]
